### PR TITLE
core: optimize performance

### PR DESCRIPTION
**Pull request by LOSEARDES77**
Optimize performance by 12983918923% and reduce project size

Use a better text editor without shit only the necessary things

Protip: vscod has more features if needed

image

### CODE REVIEW

**Comment by ivvil** [comment]
Lisp is da wae

**Comment by ivvil** [comment]
Also [doom emacs](https://github.com/doomemacs/doomemacs) exists

**Comment by ivvil** [comment]
[this](https://xkcd.com/297/)

**Comment by LOSEARDES77** [comment]
> Lisp is da wae

no

**Pull request closed without merging**
